To build a distribution kit:

Clone the git repository & cd to it

Commit any changes.

Install Dist::Zilla from CPAN (has many dependencies)
Install Dist::Zilla::Plugin::CopyFilesFromBuild
Install Dist::Zilla::Plugin::Run
Install Pod::Readme

Update the version number in lib/PKCS10.pm
Make any README changes in lib/PKCS10.pm

Update Changes

Run build:
  dzil build

The output is Crypt-PKCS10-<version>/ and .tar.gz
README, Commitlog, LICENSE, Makefile.PL, MANIFEST, META.* are auto-generated by the build.

Test the distribution:
  dzil test

To Release
 dzil release --trial
or
 dzil release

